# Generated by Django 3.2.9 on 2021-11-14 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0002_auto_20211114_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phonenumber', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer_firstname', 'customer_lastname'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_line1', models.CharField(max_length=200, null=True)),
                ('addr_line2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.customer')),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.state')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
