# Generated by Django 3.2.5 on 2021-11-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0004_auto_20211114_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
