# Generated by Django 3.2.5 on 2021-11-24 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='display_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='freespace_apiapp.designation'),
        ),
        migrations.CreateModel(
            name='Customer_Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.lead')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
