# Generated by Django 3.2.5 on 2021-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0006_auto_20211124_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
