# Generated by Django 3.2.5 on 2021-11-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0007_auto_20211124_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_followup',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='tempfile',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='tempfile',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.file'),
        ),
        migrations.AlterField(
            model_name='statustracker',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempfile',
            name='file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
