# Generated by Django 3.2.5 on 2021-11-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0008_auto_20211124_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempfile',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.lead'),
        ),
        migrations.AddField(
            model_name='tempfile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
