# Generated by Django 3.2.5 on 2021-11-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0009_auto_20211124_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempfile',
            name='file_id',
        ),
        migrations.AddField(
            model_name='file',
            name='tempfile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmp', to='freespace_apiapp.tempfile'),
        ),
    ]
