# Generated by Django 3.2.5 on 2021-11-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0010_auto_20211124_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tempfile_id',
        ),
    ]
