# Generated by Django 3.2.5 on 2021-11-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0011_remove_file_tempfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tempfile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmp', to='freespace_apiapp.tempfile'),
        ),
    ]
