# Generated by Django 3.2.5 on 2021-11-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0013_remove_file_tempfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempfile',
            name='file',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
