# Generated by Django 3.2.5 on 2021-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0014_alter_tempfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
