# Generated by Django 3.2.5 on 2021-11-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0016_auto_20211130_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
