# Generated by Django 3.2.5 on 2021-12-02 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0017_alter_customer_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcategory',
            name='sub_cat_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.sub_category'),
        ),
    ]
