# Generated by Django 3.2.5 on 2021-12-06 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0021_alter_leadcategory_sub_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Natureofwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='category_subtype',
            old_name='name',
            new_name='texture',
        ),
        migrations.RemoveField(
            model_name='category_subtype',
            name='sub_cat_id',
        ),
        migrations.RemoveField(
            model_name='project_payment',
            name='paytype',
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='updated_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project_payment',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.lead'),
        ),
        migrations.AddField(
            model_name='project_payment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Projectmanpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.lead')),
                ('manpower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.manpower')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manpowerdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('nature_of_work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.natureofwork')),
                ('project_manpower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.projectmanpower')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categorytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('lead_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.leadcategory')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.lead')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remarks'],
            },
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='cat_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.categorytype'),
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.size'),
        ),
        migrations.AddField(
            model_name='category_subtype',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freespace_apiapp.type'),
        ),
    ]
