# Generated by Django 3.2.5 on 2021-12-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0022_auto_20211206_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-id']},
        ),
    ]
