# Generated by Django 3.2.5 on 2021-12-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0023_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
    ]
