# Generated by Django 3.2.5 on 2021-12-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespace_apiapp', '0024_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='quotation_amount',
            field=models.IntegerField(null=True),
        ),
    ]
